image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn test
  artifacts:
      reports:
        junit:
          - target/surefire-reports/TEST-*.xml
          - target/failsafe-reports/TEST-*.xml
